# Создайте двумерный массив, содержащий единицы на границе и нули внутри.

In [26]:
import numpy as np1

arr = np.zeros((5, 5))
arr[[0, 1], :] = 2
arr[:, [0, -1]] = 1

print(arr)

[[1. 2. 2. 2. 1.]
 [1. 2. 2. 2. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]]


# Создайте в Excel или другом табличном редакторе таблицу, содержащую несколько численных и текстовых полей. Прочитайте ее в программу при помощи pandas.

In [24]:
import pandas as pd

data = {'Имя': ['John', 'Mike', 'Anna'],
        'Возраст': [25, 30, 35],
        'Город': ['New York', 'LA', 'London']}
df = pd.DataFrame(data)

# Сохраняем таблицу в файл
df.to_excel('table.xlsx', index=False)

df_loaded = pd.read_excel('table.xlsx')

df_loaded.head()

Имя  Возраст     Город
0  John       25  New York
1  Mike       30        LA
2  Anna       35    London

In [25]:
import pandas as pd

df = pd.read_excel('Книга1.xlsx')

df.head()

Имя  Возраст          Город
0        Анна        33        Москва
1       Иван         56          Сочи
2      Андрей        45        Москва
3       Мария        14  Екатеринбург
4  Александр         27        Москва